package com.example.slrry_10

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.slrry_10.auth.AuthServiceLocator
import com.example.slrry_10.ui.theme.SLRRY_10Theme
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider

class StartScreenActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        val authManager = AuthServiceLocator.authManager
        val firebaseAuth = FirebaseAuth.getInstance()

        // Prefer the string generated by the google-services plugin, if present.
        // This avoids manual mistakes and keeps the code working after re-downloading google-services.json.
        val defaultWebClientIdRes = resources.getIdentifier("default_web_client_id", "string", packageName)
        val defaultWebClientId = if (defaultWebClientIdRes != 0) getString(defaultWebClientIdRes).trim() else ""

        // Fallback to our manual string (kept for compatibility with older configs).
        val manualWebClientId = getString(R.string.google_web_client_id).trim()
        val webClientId = (defaultWebClientId.ifBlank { manualWebClientId }).trim()
        val gsoBuilder = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestEmail()
        if (webClientId.isNotBlank() && !webClientId.startsWith("REPLACE")) {
            gsoBuilder.requestIdToken(webClientId)
        }
        val gso = gsoBuilder.build()
        val googleClient = GoogleSignIn.getClient(this, gso)

        val googleLauncher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
            val data = result.data
            val task = GoogleSignIn.getSignedInAccountFromIntent(data)
            try {
                val account = task.getResult(ApiException::class.java)
                val token = account.idToken
                if (token.isNullOrBlank()) {
                    Toast.makeText(
                        this,
                        "Google sign-in is not configured. Ensure Google sign-in is enabled in Firebase Console, add SHA-1, and re-download google-services.json.",
                        Toast.LENGTH_LONG
                    ).show()
                    return@registerForActivityResult
                }

                val credential = GoogleAuthProvider.getCredential(token, null)
                firebaseAuth.signInWithCredential(credential)
                    .addOnSuccessListener { res ->
                        val user = res.user
                        if (user == null) {
                            Toast.makeText(this, "Google sign-in failed (no user).", Toast.LENGTH_SHORT).show()
                            return@addOnSuccessListener
                        }
                        authManager.ensureUserDoc(user, displayName = account.displayName) { _ -> }
                        startActivity(Intent(this, DashboardActivity::class.java))
                        finish()
                    }
                    .addOnFailureListener { e ->
                        Toast.makeText(this, e.message ?: "Google sign-in failed.", Toast.LENGTH_SHORT).show()
                    }
            } catch (e: Exception) {
                Toast.makeText(this, e.message ?: "Google sign-in cancelled.", Toast.LENGTH_SHORT).show()
            }
        }

        setContent {
            SLRRY_10Theme {
                Surface(modifier = Modifier.fillMaxSize(), color = Color.White) {
                    StartScreen(
                        onSignIn = {
                            // Open Login screen (Firebase will be wired later)
                            startActivity(Intent(this, LoginActivity::class.java))
                            overridePendingTransition(android.R.anim.fade_in, android.R.anim.fade_out)
                        },
                        onSignUp = {
                            // TODO: wire to real auth flow
                            startActivity(Intent(this, PasswordActivity::class.java))
                            overridePendingTransition(android.R.anim.fade_in, android.R.anim.fade_out)
                        },
                        onGoogleSignUp = {
                            googleLauncher.launch(googleClient.signInIntent)
                        }
                    )
                }
            }
        }
    }
}

@Composable
fun StartScreen(
    onSignIn: () -> Unit,
    onSignUp: () -> Unit,
    onGoogleSignUp: () -> Unit
) {
    val accentTop = Color(0xFFC8FF2F)
    val accentBottom = Color(0xFFB8FF3A)
    val accentBrush = Brush.verticalGradient(listOf(accentTop, accentBottom))
    val text = Color(0xFF0E1112)
    val muted = Color(0xFF6E757A)
    val divider = Color(0xFF111416).copy(alpha = 0.55f)

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.White)
            .padding(horizontal = 26.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        // Logo
        Text(
            text = "SLRRY",
            fontSize = 54.sp,
            fontWeight = FontWeight.Black,
            color = text,
            letterSpacing = 1.sp
        )
        Box(
            modifier = Modifier
                .padding(top = 8.dp)
                .fillMaxWidth(0.42f)
                .height(6.dp)
                .background(accentBottom, shape = RoundedCornerShape(6.dp))
        )

        Spacer(modifier = Modifier.height(56.dp))

        NeonButton(
            text = "Sign In",
            brush = accentBrush,
            textColor = text,
            onClick = onSignIn
        )
        Spacer(modifier = Modifier.height(18.dp))
        NeonButton(
            text = "Sign Up",
            brush = accentBrush,
            textColor = text,
            onClick = onSignUp
        )

        Spacer(modifier = Modifier.height(52.dp))

        // Divider line
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .height(1.dp)
                .background(divider)
        )
        Spacer(modifier = Modifier.height(34.dp))

        Text(
            text = "sign up with",
            fontSize = 18.sp,
            color = muted
        )
        Spacer(modifier = Modifier.height(18.dp))

        GoogleButton(onClick = onGoogleSignUp)
        Spacer(modifier = Modifier.height(12.dp))
    }
}

@Composable
private fun NeonButton(
    text: String,
    brush: Brush,
    textColor: Color,
    onClick: () -> Unit
) {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .height(58.dp)
            .shadow(elevation = 18.dp, shape = RoundedCornerShape(18.dp), ambientColor = Color(0x66000000))
            .background(brush = brush, shape = RoundedCornerShape(18.dp))
            .clickable { onClick() },
        contentAlignment = Alignment.Center
    ) {
        Text(
            text = text,
            fontSize = 18.sp,
            fontWeight = FontWeight.SemiBold,
            color = textColor,
            textAlign = TextAlign.Center
        )
    }
}

@Composable
private fun GoogleButton(onClick: () -> Unit) {
    Box(
        modifier = Modifier
            .size(64.dp)
            .shadow(14.dp, CircleShape, ambientColor = Color(0x33000000))
            .background(Color.White, CircleShape)
            .clickable { onClick() },
        contentAlignment = Alignment.Center
    ) {
        // Minimal Google mark approximation (keeps repo asset-free).
        Text(
            text = "G",
            fontSize = 30.sp,
            fontWeight = FontWeight.Bold,
            color = Color(0xFF4285F4) // Google blue
        )
    }
}


